In [10]:
import pandas as pd

In [11]:
data = 'state county.csv'

In [12]:
data_df = pd.read_csv(data)
data_df.head()

,Unnamed: 0,femaDeclarationString,disasterNumber,state,declarationType,declarationDate,fyDeclared,incidentType,declarationTitle,ihProgramDeclared,...,disasterCloseoutDate,fipsStateCode,fipsCountyCode,placeCode,designatedArea,declarationRequestNumber,hash,lastRefresh,id,state county
0,0,DR-4-MI,4,MI,DR,1953-06-02T04:00:00.000Z,1953,Tornado,TORNADO,0,...,NaN,26,0,0,Statewide,53004,8c9dee13124e36a9dfe2eb74e33fafad,2019-07-26T18:49:32.240Z,5d1bceafd5b39c032f2602c0,"26,0"
1,1,DR-2-TX,2,TX,DR,1953-05-15T04:00:00.000Z,1953,Tornado,TORNADO & HEAVY RAINFALL,0,...,NaN,48,0,0,Statewide,53003,c5a1a4a1030d6730d9c562cdbe7c830f,2019-07-26T18:49:32.163Z,5d1bceafd5b39c032f2602c3,"48,0"
2,2,DR-9-TX,9,TX,DR,1953-06-19T04:00:00.000Z,1953,Flood,FLOOD,0,...,NaN,48,0,0,Statewide,53010,4485da27a9218458eb2d13a6c33a4c62,2019-07-26T18:49:32.164Z,5d1bceafd5b39c032f2602c6,"48,0"
3,3,DR-11-NH,11,NH,DR,1953-07-02T04:00:00.000Z,1953,Fire,FOREST FIRE,0,...,NaN,33,0,0,Statewide,53011,86a70820dbb80e585cc01e2ce502005c,2019-07-26T18:49:32.163Z,5d1bceafd5b39c032f2602c5,"33,0"
4,4,DR-6-MI,6,MI,DR,1953-06-09T04:00:00.000Z,1953,Tornado,TORNADO,0,...,NaN,26,0,0,Statewide,53007,d3ae03a5caa78ae1c8b6052e5e29a97d,2019-07-26T18:49:32.163Z,5d1bceafd5b39c032f2602c2,"26,0"

In [9]:
df =data_df [['disasterNumber','fipsStateCode','fyDeclared','declarationType','incidentType','fipsCountyCode',('state county')]]
df.head()

,disasterNumber,fipsStateCode,fyDeclared,declarationType,incidentType,fipsCountyCode,state county
0,4,26,1953,DR,Tornado,0,"26,0"
1,2,48,1953,DR,Tornado,0,"48,0"
2,9,48,1953,DR,Flood,0,"48,0"
3,11,33,1953,DR,Fire,0,"33,0"
4,6,26,1953,DR,Tornado,0,"26,0"

In [13]:
df.to_csv('disaster FEMA2.csv')